Foregin Invester and Domestic Invester

In [15]:
import requests
import pandas as pd

In [16]:
import requests
import pandas as pd
url = "https://webapi.niftytrader.in/webapi/Resource/fii-cash-month?Date=2023-11"

response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the JSON data
    data = response.json()
else:
    print(f"Error: Unable to fetch data. Status code: {response.status_code}")

In [17]:
maindata = data['resultData']['data']
df = pd.DataFrame(maindata)
df['created_at'] = df['created_at'].apply(lambda x: x.split('T')[0])
df = df.drop_duplicates()

In [18]:
df['created_at'] = pd.to_datetime(df['created_at']).dt.date
grouped_df = df.groupby(['created_at', 'category'])['net_value'].sum().reset_index()
pivot_df = grouped_df.pivot(index='created_at', columns='category', values='net_value').reset_index()
pivot_df = pivot_df.rename(columns={'FII/FPI': 'FII_Market_cap', 'DII': 'DII_Market_cap'})
pivot_df['Total_Market_cap'] = pivot_df['FII_Market_cap'] + pivot_df['DII_Market_cap']
pivot_df = pivot_df.fillna(0)
pivot_df

category  created_at  DII_Market_cap  FII_Market_cap  Total_Market_cap
0         2023-11-01         1622.05        -1816.91           -194.86
1         2023-11-02         1380.15        -1261.19            118.96
2         2023-11-03          402.69          -12.43            390.26
3         2023-11-06          595.70         -549.37             46.33
4         2023-11-07          700.28         -497.21            203.07
5         2023-11-08          524.47          -84.55            439.92
6         2023-11-09         1512.14        -1712.33           -200.19
7         2023-11-10          822.64         -261.81            560.83
8         2023-11-13          476.55         -950.30           -473.75
9         2023-11-15          609.82          550.19           1160.01
10        2023-11-16          705.65          957.25           1662.90
11        2023-11-17         -565.48         -477.76          -1043.24
12        2023-11-20           77.77         -645.72           -567.95
13        2023-11-21          721.52         -455.59            265.93
14        2023-11-22          721.24         -306.56            414.68
15        2023-11-23          457.39          255.53            712.92
16        2023-11-24          134.46         2625.21           2759.67
17        2023-11-28         1324.98          783.82           2108.80
18        2023-11-29         2360.81           71.91           2432.72
19        2023-11-30         -780.32         8147.85           7367.53