In [27]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
import yfinance as yf
import pandas as pd
from collections import Counter

# OUR DATA

In [28]:
symbol = '^NSEI'
period = '3d'
interval = "15m"
ticker = yf.Ticker(symbol)

df = ticker.history(period=period, interval=interval)
df.reset_index(drop=False, inplace=True)

In [29]:
df['Datetime'] = pd.to_datetime(df['Datetime'])

In [30]:
df['Date'] = df['Datetime'].dt.date
df['Time'] = df['Datetime'].dt.time
date_range = pd.DatetimeIndex(df['Date'])

In [31]:
df.drop(columns=["Volume","Dividends","Stock Splits"],inplace=True)

current = df.tail(1)

# DATE

In [32]:
current_date = datetime.datetime.now().strftime('%Y-%m-%d')
print("current_date :",current_date)
date_tuples = [(date.year, date.month, date.day) for date in set(df['Datetime'].dt.date)]
date_tuples.sort()
formatted_dates = [f'{date[0]:04d}-{date[1]:02d}-{date[2]:02d}' for date in date_tuples]
previous_day_data = df[df['Datetime'].dt.date == pd.to_datetime('2023-09-01').date()]
previous_date= formatted_dates[-2]
print("previous_data :",previous_date)

current_date : 2023-09-07
previous_data : 2023-09-05

In [33]:
previous_day_data = df[df['Datetime'].dt.date <= pd.to_datetime(previous_date).date() ]

## PREVIOUS DAY HIGH LOW

In [34]:
max_high_row = previous_day_data[previous_day_data['High'] == previous_day_data['High'].max()]["High"]
min_low_row = previous_day_data[previous_day_data['Low'] == previous_day_data['Low'].min()]["Low"]
print("Max High:",max_high_row)
print("Max Low:",min_low_row)

Max High: 35    19586.900391
Name: High, dtype: float64
Max Low: 5    19433.150391
Name: Low, dtype: float64

## MAX AND MIN CANDLES CONFLICT

In [49]:
def count_m_values(row):
    n = 10
    m_counts = {}
    for m in range(int(row['Low']) - n, int(row['High']) + n + 1):
        m_counts[m] = m_counts.get(m, 0) + 1
    return pd.Series(m_counts)

m_counts_df = previous_day_data.apply(count_m_values, axis=1).fillna(0).astype(int)

total_counts = m_counts_df.sum()
max_candle_re = total_counts.reset_index().rename(columns={'index': 'm', 0: 'Count'}).sort_values(by='Count', ascending=False)
max_candle_re['m_diff'] = max_candle_re['m'].diff().abs()
filtered_max_candle_re = max_candle_re[(max_candle_re['m_diff'] >= 20)]
filtered_max_candle_re = filtered_max_candle_re.drop('m_diff', axis=1)
def find_up_low(row):
    if row[0]>= int(current['Close'].values) :
        return "RESISTANCE"
    else:
        return "SUPPORT"
filtered_max_candle_re["Status"] = filtered_max_candle_re.apply(find_up_low,axis=1)

In [50]:
filtered_max_candle_re

         m  Count      Status
128  19551     19  RESISTANCE
151  19574     18  RESISTANCE
127  19550     17  RESISTANCE
80   19503     16  RESISTANCE
121  19544     16  RESISTANCE
154  19577     16  RESISTANCE
101  19524     16  RESISTANCE
153  19576     16  RESISTANCE
95   19518     16  RESISTANCE
155  19578     16  RESISTANCE
120  19543     16  RESISTANCE
96   19519     15  RESISTANCE
124  19547     15  RESISTANCE
89   19512     15  RESISTANCE
100  19523     15  RESISTANCE
76   19499     15  RESISTANCE
102  19525     15  RESISTANCE
77   19500     15  RESISTANCE
156  19579     15  RESISTANCE
126  19549     15  RESISTANCE
82   19505     14  RESISTANCE
160  19583     14  RESISTANCE
85   19508     14  RESISTANCE
123  19546     14  RESISTANCE
163  19586     13  RESISTANCE
113  19536     13  RESISTANCE
161  19584     13  RESISTANCE
97   19520     13  RESISTANCE
67   19490     13  RESISTANCE
106  19529     12  RESISTANCE
63   19486     12  RESISTANCE
111  19534     12  RESISTANCE
66   19489     12  RESISTANCE
164  19587     11  RESISTANCE
109  19532     11  RESISTANCE
61   19484     11  RESISTANCE
107  19530     11  RESISTANCE
43   19466     10  RESISTANCE
165  19588     10  RESISTANCE
45   19468     10  RESISTANCE
166  19589      9  RESISTANCE
33   19456      9  RESISTANCE
57   19480      9  RESISTANCE
32   19455      8  RESISTANCE
60   19483      8  RESISTANCE
167  19590      8  RESISTANCE
28   19451      7  RESISTANCE
170  19593      6  RESISTANCE
24   19447      6  RESISTANCE
171  19594      3  RESISTANCE
1    19424      2  RESISTANCE
172  19595      2  RESISTANCE
0    19423      1  RESISTANCE
173  19596      1  RESISTANCE

In [51]:
int(current['Close'].values)

19618